name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3307
        options: --health-cmd "mysqladmin ping -h 127.0.0.1" --health-interval 20s --health-timeout 10s --health-retries 10
    steps:
      - uses: actions/checkout@v2
      - name: Check MySQL Version
        run: echo 'select version();' | mysql -h 0.0.0.0 --port 3307 -u root -proot
